apiVersion: v1
kind: Service
metadata:
  name: data-processor
  namespace: iot
  labels:
    app: data-processor
spec:
  type: ClusterIP
  selector:
    app: data-processor
  ports:
    - port: 8080
      targetPort: 8080
